name: Reso
description: A new Flutter project.

publish_to: 'none' 

version: 1.1.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.0.0
  shared_preferences: any
  geolocator: ^5.3.1
  build_runner: ^1.7.2
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.4.7
  curved_navigation_bar: ^0.3.2
  qr_code_scanner: 0.0.12
  qr_flutter: ^3.1.0
  flutter_spinkit: ^4.1.2
  flutter_circular_chart: 0.1.0
  uuid: 2.0.4
  datetime_picker_formfield: ^1.0.0
  location: ^3.0.2
  font_awesome_flutter: '>= 4.7.0'
  equatable: ^1.1.1
  dartz: ^0.9.1
  mockito: ^4.1.1
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  bloc: ^4.0.0
  validators: ^2.0.0
  get_it: ^4.0.2
  flutter_bloc: ^4.0.0
  cached_network_image: ^2.2.0+1
  auto_route: ^0.5.0
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.3+3
  flare_flutter: ^2.0.3
  maps_launcher: ^1.2.0
  json_serializable: ^3.3.0
  firebase_dynamic_links: ^0.5.3
  share: ^0.6.4+3

dependency_overrides:
  build:
    git:
      url: https://github.com/dart-lang/build.git
      path: build
  build_resolvers:
    git:
      url: https://github.com/dart-lang/build.git
      path: build_resolvers

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.5.0

flutter_icons:
  image_path_android: "assets/launcher/Android/App Icon/GooglePlay.png"
  image_path_ios: "assets/launcher/iOS/iTunesArtwork@2x.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/launcher/Android/Adaptive App Icon/App Icon Back.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/Android/Adaptive App Icon/App Icon Front.png"


flutter:

  uses-material-design: true

  assets:
     - assets/
     - lib/lang/